In [7]:
import numpy as np

devices = ["test1", "test2", "test3"]
distances = [0, 12.0, 13.0, 21.0, 0, 23.0, 31.0, 32.0, 0]


In [9]:
def convert_list_to_matrix(list) -> np.ndarray:
    len_devices = len(devices)
    matrix = np.empty((len_devices, len_devices))
    zeile = 0
    for list_index in range(0, len(list)):
        spalte = list_index % len_devices
        if spalte == 0 and list_index != 0:
            zeile += 1

        matrix[zeile, spalte] = list[list_index]

    return matrix

print(convert_list_to_matrix(distances))

[[ 0. 12. 13.]
 [21.  0. 23.]
 [31. 32.  0.]]
