In [1]:
import numpy as np

In [5]:
test = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(test)

print(mean)

5.5


In [6]:
result_1 = 10 - mean

print(result_1)

4.5


In [7]:
buf = np.array([])
for i in test:
    buf = np.append(buf, 10 - i)
    print(buf)

result_2 = np.mean(buf)
print(result_2)

[9.]
[9. 8.]
[9. 8. 7.]
[9. 8. 7. 6.]
[9. 8. 7. 6. 5.]
[9. 8. 7. 6. 5. 4.]
[9. 8. 7. 6. 5. 4. 3.]
[9. 8. 7. 6. 5. 4. 3. 2.]
[9. 8. 7. 6. 5. 4. 3. 2. 1.]
[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
4.5
