In [1]:
import numpy as np

In [2]:
edm_measured = np.array(
        [
            [0, 162.1613, 162.2531],
            [162.1270, 0, 162.2449],
            [162.2155, 162.2582, 0],
        ]
    )

edm_measured = edm_measured * (1/299702547)

print(edm_measured)

[[0.00000000e+00 5.41074147e-07 5.41380451e-07]
 [5.40959700e-07 0.00000000e+00 5.41353090e-07]
 [5.41254993e-07 5.41397468e-07 0.00000000e+00]]


In [3]:
edm_real = np.array(
        [
            [0, 7.914, 7.914],
            [7.914, 0, 7.914],
            [7.914, 7.914, 0],
        ]
    )

edm_real = edm_real * (1/299702547)

print(edm_real)

[[0.0000000e+00 2.6406182e-08 2.6406182e-08]
 [2.6406182e-08 0.0000000e+00 2.6406182e-08]
 [2.6406182e-08 2.6406182e-08 0.0000000e+00]]
